apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-nginx-conf
  namespace: hw11-other
data:
  default.conf: |
    server {
      listen 80;
      location / {
        default_type text/plain;
        return 200 "hello from payments in hw11-other, pod $hostname\n";
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: hw11-other
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: conf
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: conf
          configMap:
            name: payments-nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: hw11-other
  labels:
    app: payments
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
