apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: hw14
  labels:
    app: netshoot
    role: debug
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "7200"
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
