apiVersion: v1
kind: Pod
metadata:
  name: errimagepull-fixed
  namespace: hw14
  labels:
    app: yatri-web
    scenario: errimagepull
    state: fixed
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
