apiVersion: v1
kind: Pod
metadata:
  name: pending-nodeselector-broken
  namespace: hw14
  labels:
    app: cache
    scenario: pending-nodeselector
    state: broken
spec:
  nodeSelector:
    disktype: nvme-ssd
  containers:
    - name: cache
      image: nginx:1.27-alpine
