apiVersion: v1
kind: Pod
metadata:
  name: core-pod
  namespace: hw10
  labels:
    app: core-pod
spec:
  containers:
    - name: web
      image: nginx:alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "20m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
