apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: core-rs
  namespace: hw10
  labels:
    app: core-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: core-rs
  template:
    metadata:
      labels:
        app: core-rs
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
