apiVersion: v1
kind: ServiceAccount
metadata:
  name: yatri-app-sa
  namespace: hw12
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yatri-config-reader
  namespace: hw12
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yatri-config-reader-binding
  namespace: hw12
subjects:
  - kind: ServiceAccount
    name: yatri-app-sa
    namespace: hw12
roleRef:
  kind: Role
  name: yatri-config-reader
  apiGroup: rbac.authorization.k8s.io
