apiVersion: v1
kind: ConfigMap
metadata:
  name: allhosts-nginx-conf
  namespace: hw14
  labels:
    scenario: pod-networking
    state: fixed
data:
  default.conf: |
    server {
        listen 0.0.0.0:80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: netbind-fixed
  namespace: hw14
  labels:
    app: netbind
    scenario: pod-networking
    state: fixed
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
  volumes:
    - name: conf
      configMap:
        name: allhosts-nginx-conf
