apiVersion: v1
kind: Service
metadata:
  name: shop-api-svc
  namespace: hw14
  labels:
    scenario: service-connectivity
    state: broken
spec:
  type: ClusterIP
  selector:
    app: shop-api-v2
  ports:
    - name: http
      port: 80
      targetPort: 80
