apiVersion: v1
kind: Pod
metadata:
  name: imagepullbackoff-broken
  namespace: hw14
  labels:
    app: yatri-api
    scenario: imagepullbackoff
    state: broken
spec:
  containers:
    - name: api
      image: yatri-api-service:v999-invalid
