apiVersion: v1
kind: Pod
metadata:
  name: imagepullbackoff-fixed
  namespace: hw14
  labels:
    app: yatri-api
    scenario: imagepullbackoff
    state: fixed
spec:
  containers:
    - name: api
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
