apiVersion: v1
kind: Pod
metadata:
  name: state-pending-cpu
  namespace: hw10
  labels:
    demo: lifecycle
spec:
  containers:
    - name: greedy
      image: nginx:alpine
      resources:
        requests:
          cpu: "64"
          memory: "256Gi"
