apiVersion: v1
kind: Pod
metadata:
  name: state-imagepull
  namespace: hw10
  labels:
    demo: lifecycle
spec:
  containers:
    - name: broken
      image: nginx:this-tag-does-not-exist-999
      resources:
        requests:
          cpu: "10m"
          memory: "16Mi"
