server {
    listen 80;
    server_name localhost;

    add_header X-Served-By "nginx-app-docker-homework" always;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}
