apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo
  namespace: hw13
spec:
  containers:
    - name: web
      image: nginx:1.27
      ports:
        - containerPort: 80
      lifecycle:
        postStart:
          exec:
            command:
              - sh
              - -c
              - "echo ok > /usr/share/nginx/html/healthz"
      livenessProbe:
        httpGet:
          path: /healthz
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 2
        failureThreshold: 3
