apiVersion: v1
kind: Service
metadata:
  name: claim-check-api
  namespace: hw17
  labels:
    app: claim-check-api
    session: "17"
spec:
  type: NodePort
  selector:
    app: claim-check-api
  ports:
    - name: http
      port: 5017
      targetPort: http
      nodePort: 30170
