apiVersion: v1
kind: PersistentVolume
metadata:
  name: hw13-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hw13-manual
  hostPath:
    path: /tmp/hw13-static-data
    type: DirectoryOrCreate
