apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: hw13
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hw13-manual
  resources:
    requests:
      storage: 500Mi
