#!/bin/bash
#
# sysinfo.sh - System Information Script
#
# DevOps Homework - Shell Scripting - Task 1
#
# What it does:
#   - Prints the current date, hostname and username.
#   - Prints disk usage (df -h) and the list of running processes (ps aux).
#   - Asks the user (via `read -p`) for a "report label" that is used to
#     name an output directory.
#   - Creates that directory with `mkdir -p`, creates an empty report file
#     in it with `touch`, then overwrites that file with the running
#     process list using `>` output redirection.
#   - Prints a final summary of everything that was created.
#
# Usage:
#   ./sysinfo.sh                      (interactive - will prompt you)
#   echo "myreport" | ./sysinfo.sh    (non-interactive - piped input)
#   ./sysinfo.sh <<< "myreport"       (non-interactive - here-string)
#
set -euo pipefail

# ---------------------------------------------------------------------------
# 1. Variables - gather system information via command substitution
# ---------------------------------------------------------------------------
current_date="$(date)"
current_hostname="$(hostname)"
current_user="$(whoami)"
kernel_info="$(uname -srm)"
uptime_info="$(uptime -p 2>/dev/null || uptime)"

# ---------------------------------------------------------------------------
# 2. Section header helper - keeps the `echo` output tidy and consistent
# ---------------------------------------------------------------------------
print_section() {
    local title="$1"
    echo ""
    echo "==============================================================="
    echo " ${title}"
    echo "==============================================================="
}

# ---------------------------------------------------------------------------
# 3. Basic system information
# ---------------------------------------------------------------------------
print_section "SYSTEM INFORMATION"
echo "Date       : ${current_date}"
echo "Hostname   : ${current_hostname}"
echo "User       : ${current_user}"
echo "Kernel     : ${kernel_info}"
echo "Uptime     : ${uptime_info}"

# ---------------------------------------------------------------------------
# 4. Disk usage
# ---------------------------------------------------------------------------
print_section "DISK USAGE (df -h)"
df -h

# ---------------------------------------------------------------------------
# 5. Running processes (shown on screen first)
# ---------------------------------------------------------------------------
print_section "RUNNING PROCESSES (ps aux) - first 10 lines shown here"
ps aux | head -n 10

# ---------------------------------------------------------------------------
# 6. Take user input for the report label / output directory name
# ---------------------------------------------------------------------------
print_section "REPORT SETUP"
read -p "Enter a label for this report (used as the output directory name): " report_label

# Guard against an empty answer so mkdir/touch always get a sane name.
if [ -z "${report_label}" ]; then
    report_label="sysinfo_report"
    echo "No label entered - defaulting to \"${report_label}\""
fi

echo "Using report label: \"${report_label}\""

# ---------------------------------------------------------------------------
# 7. Create the output directory and the report file
# ---------------------------------------------------------------------------
output_dir="./${report_label}"
output_file="${output_dir}/processes.txt"

mkdir -p "${output_dir}"
echo "Created directory : ${output_dir}"

touch "${output_file}"
echo "Created file      : ${output_file}"

# ---------------------------------------------------------------------------
# 8. Store the FULL running-process list in the file using > redirection
# ---------------------------------------------------------------------------
ps aux > "${output_file}"
process_count="$(wc -l < "${output_file}")"
echo "Wrote $(( process_count - 1 )) running processes (plus a header line) to ${output_file}"

# Also drop a small metadata file in the same directory, purely for extra
# context in the submission - demonstrates another > redirection + variables.
info_file="${output_dir}/system_info.txt"
{
    echo "Report label : ${report_label}"
    echo "Generated by : ${current_user}"
    echo "Generated on : ${current_date}"
    echo "Host         : ${current_hostname}"
} > "${info_file}"
echo "Created file      : ${info_file}"

# ---------------------------------------------------------------------------
# 9. Final summary
# ---------------------------------------------------------------------------
print_section "SUMMARY"
echo "Report label      : ${report_label}"
echo "Output directory  : ${output_dir}"
echo "Files created     :"
echo "  - ${output_file}  ($(wc -l < "${output_file}") lines)"
echo "  - ${info_file}"
echo ""
echo "Done. Run 'ls -lR ${output_dir}' to inspect the created files."
